=== GoFund-UST/smart-contracts/contracts/factory/schema/instantiate_msg.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "InstantiateMsg",
  "type": "object",
  "required": [
    "anchor_pool_code_id",
    "dp_code_id",
    "fee_amount",
    "fee_collector",
    "fee_max",
    "fee_reset_every_num_blocks",
    "money_market"
  ],
  "properties": {
    "anchor_pool_code_id": {
      "type": "integer",
      "format": "uint64",
      "minimum": 0.0
    },
    "dp_code_id": {
      "type": "integer",
      "format": "uint64",
      "minimum": 0.0
    },
    "fee_amount": {
      "type": "string"
    },
    "fee_collector": {
      "type": "string"
    },
    "fee_max": {
      "$ref": "#/definitions/Uint256"
    },
    "fee_reset_every_num_blocks": {
      "type": "integer",
      "format": "uint64",
      "minimum": 0.0
    },
    "homepage": {
      "type": [
        "string",
        "null"
      ]
    },
    "money_market": {
      "type": "string"
    },
    "nft_code_id": {
      "type": [
        "integer",
        "null"
      ],
      "format": "uint64",
      "minimum": 0.0
    }
  },
  "definitions": {
    "Uint256": {
      "type": "string"
    }
  }
}

=== GoFund-UST/smart-contracts/contracts/factory/factory_init.json
{
  "dp_code_id": 1572,
  "fee_amount": "0.05",
  "fee_collector": "terra1yt8xwehw3mngc7h2z09utf32cgpdpe09lke902",
  "fee_max": "0",
  "fee_reset_every_num_blocks": 0,
  "money_market": "terra15dwd5mj8v59wpj0wvt233mf5efdff808c5tkal",
  "anchor_pool_code_id":  47989,
  "nft_code_id": 47850,
  "homepage": "https://gofundust.money"
}
