=== GoFund-UST/smart-contracts/contracts/pool-lsd/schema/instantiate_msg.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "InstantiateMsg",
  "type": "object",
  "required": [
    "beneficiary",
    "dp_code_id",
    "fee_amount",
    "fee_collector",
    "fee_max",
    "fee_reset_every_num_blocks",
    "money_market",
    "owner_can_change_config",
    "pool_description",
    "pool_name",
    "pool_title"
  ],
  "properties": {
    "beneficiary": {
      "type": "string"
    },
    "dp_code_id": {
      "type": "integer",
      "format": "uint64",
      "minimum": 0.0
    },
    "fee_amount": {
      "type": "string"
    },
    "fee_collector": {
      "type": "string"
    },
    "fee_max": {
      "$ref": "#/definitions/Uint256"
    },
    "fee_reset_every_num_blocks": {
      "type": "integer",
      "format": "uint64",
      "minimum": 0.0
    },
    "money_market": {
      "type": "string"
    },
    "nft_collection_active": {
      "type": [
        "integer",
        "null"
      ],
      "format": "uint64",
      "minimum": 0.0
    },
    "nft_collection_redeemed": {
      "type": [
        "integer",
        "null"
      ],
      "format": "uint64",
      "minimum": 0.0
    },
    "nft_contract": {
      "type": [
        "string",
        "null"
      ]
    },
    "owner_can_change_config": {
      "type": "boolean"
    },
    "pool_description": {
      "type": "string"
    },
    "pool_name": {
      "type": "string"
    },
    "pool_title": {
      "type": "string"
    }
  },
  "definitions": {
    "Uint256": {
      "type": "string"
    }
  }
}

=== GoFund-UST/smart-contracts/contracts/pool-anchor/pool_init.json
{
  "beneficiary": "terra1n3g37dsdlv7ryqftlkef8mhgqj4ny7p8v78lg7",
  "dp_code_id": 1572,
  "fee_amount": "0.05",
  "fee_collector": "terra1yt8xwehw3mngc7h2z09utf32cgpdpe09lke902",
  "fee_max": "0",
  "fee_reset_every_num_blocks": 0,
  "money_market": "terra15dwd5mj8v59wpj0wvt233mf5efdff808c5tkal",
  "pool_name": "TEST",
  "pool_title": "GoFund US(T) Test Fund",
  "pool_description": "This is a test fund. Please do not put real money into it",
  "owner_can_change_config": false
}
